package com.sy.cloud.infra.enums;

import com.sy.cloud.framework.common.enums.RpcConstants;

/**
 * API 相关的枚举
 *
 * @author 三壹科技
 */
public class ApiConstants {
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas
asdasasdasdasdasasdasas